using FraudDetection.Domain.Common;

namespace FraudDetection.Domain.Entities;

/// <summary>
/// A natural language fraud investigation report generated by an LLM, summarizing
/// detected alerts and transaction patterns for a customer or a time window.
/// </summary>
public sealed class FraudReport : Entity
{
    // Private parameterless constructor for EF Core.
    private FraudReport() { }

    public FraudReport(
        string markdownContent,
        DateTime windowFrom,
        DateTime windowTo,
        Guid? customerId = null)
    {
        MarkdownContent = markdownContent;
        WindowFrom = windowFrom;
        WindowTo = windowTo;
        CustomerId = customerId;
        GeneratedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// The customer this report is scoped to.
    /// Null when the report covers all customers in a time window.
    /// </summary>
    public Guid? CustomerId { get; private set; }

    /// <summary>Start of the analysis window (UTC, inclusive).</summary>
    public DateTime WindowFrom { get; private set; }

    /// <summary>End of the analysis window (UTC, inclusive).</summary>
    public DateTime WindowTo { get; private set; }

    /// <summary>When the LLM generated this report (UTC).</summary>
    public DateTime GeneratedAt { get; private set; }

    /// <summary>
    /// Full report content in Markdown format as returned by the LLM.
    /// Typically includes sections: Executive Summary, Detected Patterns,
    /// Affected Customers, Timeline of Events, Recommendations, Risk Assessment.
    /// </summary>
    public string MarkdownContent { get; private set; } = default!;

    /// <summary>Number of <see cref="FraudAlert"/> records included in this report.</summary>
    public int AlertCount { get; private set; }

    /// <summary>Number of <see cref="TransactionSnapshot"/> records analysed for this report.</summary>
    public int TransactionCount { get; private set; }

    /// <summary>Sets the snapshot counts captured at report-generation time.</summary>
    public void SetCounts(int alertCount, int transactionCount)
    {
        AlertCount = alertCount;
        TransactionCount = transactionCount;
    }
}
